### ISSUE TITLE
Maintain

### ISSUE THREAD

**Issue by y7usuf** [slively/loopback-db-migrate#14]
I want to maintain this repo, you can transfer ownership to me if you want.

**Comment by doublemarked** [comment]
@slively what about referring people to https://github.com/fullcube/loopback-component-migrate, which diverged a little from loopback-db-migrate but still quite similar. I see @mrfelton is still actively working on that, and I know they are quite committed to Loopback. And @y7usuf, this might be a good way for us to all to work together on migrations rather than splintering into separate small projects.

**Comment by jcolemorrison** [comment]
That's a good idea.  Maybe if we can get people centralized something solid and well maintained by a larger group can occur.  It still shocks me that a more formal system of migration hasn't been added to the core of loopback.

**Comment by slively** [comment]
I like that idea better, updated the header on the README, thank you.
